version: 2.1

jobs:
  ########### Build Heroes Service ###########
  build-heroes-service:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [heroes-build]
      - run:
          name: Build Heroes Service
          command: |
            cd heroes
            npm i
      - save_cache:
          paths: [heroes/node_modules]
          key: heroes-build

  ########### Build Threats Service ###########
  build-threats-service:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [threats-build]
      - run:
          name: Build Threats Service
          command: |
            cd threats
            npm i
      - save_cache:
          paths: [threats/node_modules]
          key: threats-build

  ########### Lint Heroes Service ###########
  lint-heroes-service:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [heroes-build]
      - run:
          name: Lint Heroes Service
          command: |
            cd heroes
            npm run lint

  ########### Lint Threats Service ###########
  lint-threats-service:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [threats-build]
      - run:
          name: Lint Threats Service
          command: |
            cd threats
            npm run lint

workflows:
  default:
    jobs:
      - build-heroes-service
      - build-threats-service
      - lint-heroes-service:
          requires: [build-heroes-service]
      - lint-threats-service:
          requires: [build-threats-service]