apiVersion: v1
kind: Service
metadata:
  name: heroes-service
  labels:
    app: heroes-service
spec:
  type: LoadBalancer
  selector:
    app: heroes-service
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-service
  labels:
    app: heroes-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes-service
  template:
    metadata:
      labels:
        app: heroes-service
    spec:
      containers:
        - image: "${AWS_ECR_ACCOUNT_URL}/heroes/latest-${CIRCLE_BUILD_NUM}"
          imagePullPolicy: Always
          name: heroes-service
          ports:
            - containerPort: 8081
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate