apiVersion: v1
kind: Service
metadata:
  name: threats-service
  labels:
    app: threats-service
spec:
  type: LoadBalancer
  selector:
    app: threats-service
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threats-service
  labels:
    app: threats-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threats-service
  template:
    metadata:
      labels:
        app: threats-service
    spec:
      containers:
        - image: 338416168655.dkr.ecr.us-west-2.amazonaws.com/threats:latest
          imagePullPolicy: Always
          name: threats-service
          ports:
            - containerPort: 8082
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
